version: '3.4'

#configs: 
  #IMAGE_TAG = 'latest'

services:
  musicals:
    image: ${DOCKER_REGISTRY-}musicals:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Musicals/Dockerfile

  ui:
    image: ${DOCKER_REGISTRY-}ui:${IMAGE_TAG}
    build:
      context: .
      dockerfile: UI/Dockerfile


  payments:
    image: ${DOCKER_REGISTRY-}payments:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Payments/Dockerfile

