version: '3.4'

services:
  musicals:
    #deploy:
    #  replicas: 2
    image: ${DOCKER_REGISTRY-}musicals
    build:
      context: .
      dockerfile: Musicals/Dockerfile

  ui:
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile


  payments:
    image: ${DOCKER_REGISTRY-}payments
    build:
      context: .
      dockerfile: Payments/Dockerfile

